/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mandalorian.gltf --transform 
Files: mandalorian.gltf [12.57MB] > mandalorian-transformed.glb [4.11MB] (67%)
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mandalorian-grogu-the-force-1cbbc8a231154426ade7d3b11cf5bb0e
Title: Mandalorian - Grogu ( The force )
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
	const { nodes, materials } = useGLTF('/mandalorian-transformed.glb');
	return (
		<group {...props} dispose={null}>
			<meshStandardMaterial color="black" />
			<mesh geometry={nodes.BY_fur_fur_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				<meshStandardMaterial color="black" />
			</mesh>
			<mesh geometry={nodes.BY_skin_skin_0.geometry} material={materials.skin} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="darkgreen" />
			</mesh>
			<mesh geometry={nodes.BY_skin_nail_0.geometry} material={materials.nail} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="yellow" />
			</mesh>
			<mesh geometry={nodes.BY_skin_oral_0.geometry} material={materials.oral} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="black" />
			</mesh>
			<mesh geometry={nodes.BY_skin_pupil_0.geometry} material={materials.pupil} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="black" />
			</mesh>
			<mesh geometry={nodes.BY_skin_eyes_b_0.geometry} material={materials.eyes_b} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="red" />
			</mesh>
			<mesh geometry={nodes.BY_skin_eyes_w_0.geometry} material={materials.eyes_w} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				{' '}
				<meshStandardMaterial color="black" />
			</mesh>
			<mesh geometry={nodes.BY_skin_lens_0.geometry} material={materials.lens} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
				{' '}
				<meshStandardMaterial color="black" />
			</mesh>
			<mesh
				geometry={nodes.cloth_shape_001_BY_cloth3_0.geometry}
				material={materials.BY_cloth3}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				{' '}
				<meshStandardMaterial color="#B59410" />
			</mesh>
			<mesh
				geometry={nodes.cloth_shape_002_BY_cloth2_0.geometry}
				material={materials.BY_cloth2}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				{' '}
				<meshStandardMaterial color="#B59410" />
			</mesh>
			<mesh
				geometry={nodes.cloth_shape_002_BY_cloth1_0.geometry}
				material={materials.BY_cloth1}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				{' '}
				<meshStandardMaterial color="#B59410" />
			</mesh>

			<mesh
				geometry={nodes.Sphere_sphere1_0.geometry}
				material={materials.sphere1}
				position={[-0.099, 0.277, 0.174]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				{' '}
				<meshStandardMaterial color="#B59410" />
			</mesh>
			<mesh
				geometry={nodes.Sphere_sphere2_0.geometry}
				material={materials.sphere2}
				position={[-0.099, 0.277, 0.174]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				{' '}
				<meshStandardMaterial color="blue" />
			</mesh>
		</group>
	);
}

useGLTF.preload('/mandalorian-transformed.glb');
