/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 turbo.gltf --transform 
Files: turbo.gltf [16.87MB] > turbo-transformed.glb [1.14MB] (93%)
Author: Nokken (https://sketchfab.com/nokken)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-turbocharger-071da6d19c7541d7b3a87c3bc12085ca
Title: Sci-fi turbocharger
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { PerspectiveCamera, RenderTexture } from '@react-three/drei';

export default function Model(props) {
	const { nodes, materials } = useGLTF('/turbo-transformed.glb');
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_2.geometry}
				material={materials['ZenUV_Generic_Material.002']}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.04}
			></mesh>
		</group>
	);
}

useGLTF.preload('/turbo-transformed.glb');
